BEGIN;
ALTER TABLE "JournalLine" DROP CONSTRAINT IF EXISTS "JournalLine_account_check";
ALTER TABLE "JournalLine" ADD CONSTRAINT "JournalLine_account_check" CHECK ("account" IN ('CASH','BANK','LEGACY_FUNDS','RECEIVABLE','PAYABLE','EQUIPMENT','OWNER_CAPITAL','OWNER_DRAWINGS','LOAN','REVENUE_SERVICE','REVENUE_PRODUCT','EXPENSE_SUPPLIES','EXPENSE_OPERATING','EXPENSE_INTEREST','VAT_INPUT','VAT_OUTPUT'));
CREATE TABLE IF NOT EXISTS "JournalDocument" (
 "entryId" UUID PRIMARY KEY REFERENCES "JournalEntry"("id") ON DELETE CASCADE,
 "type" TEXT NOT NULL CHECK ("type" IN ('INVOICE','RECEIPT','EXEMPT','HONORARIUM','SUPPORT')),
 "folio" TEXT NOT NULL, "rut" TEXT NOT NULL,
 "vat" INTEGER NOT NULL CHECK ("vat" >= 0),
 "recoverable" BOOLEAN NOT NULL DEFAULT FALSE,
 "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 CHECK (NOT "recoverable" OR "type" = 'INVOICE'),
 CHECK ("type" NOT IN ('EXEMPT','HONORARIUM','SUPPORT') OR "vat" = 0)
);
ALTER TABLE "JournalDocument" ENABLE ROW LEVEL SECURITY;
COMMIT;
