BEGIN;
CREATE TABLE IF NOT EXISTS "TaxProfile" (
 "id" INTEGER PRIMARY KEY CHECK ("id"=1),
 "treatment" TEXT NOT NULL DEFAULT 'UNKNOWN' CHECK ("treatment" IN ('UNKNOWN','AFFECTED','EXEMPT')),
 "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO "TaxProfile" ("id") VALUES (1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS "ReceiptSubmission" (
 "requestId" UUID PRIMARY KEY,
 "entryId" UUID NOT NULL UNIQUE REFERENCES "JournalEntry"("id") ON DELETE CASCADE,
 "payload" JSONB NOT NULL,
 "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE "TaxProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReceiptSubmission" ENABLE ROW LEVEL SECURITY;
COMMIT;
